# Generated by Django 4.2.6 on 2023-10-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_cases', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('mandatory_operation', models.CharField(choices=[('+', 'add'), ('-', 'sub'), ('*', 'mul'), ('÷', 'div'), ('.', 'none')], max_length=2)),
                ('optional_operation', models.CharField(choices=[('+', 'add'), ('-', 'sub'), ('*', 'mul'), ('÷', 'div'), ('.', 'none')], default='.', max_length=2)),
                ('from_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathador.board')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathador.board')),
                ('on_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathador.case')),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_face', models.IntegerField()),
                ('last_number_throws', models.IntegerField(default=0)),
                ('from_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathador.board')),
            ],
        ),
    ]
